#From https://shop.apolloautomation.cloud/collections/sensors
alias: Apollo Holiday
description: ""
trigger:
  - platform: event
    event_type: ""
condition: []
action:
  - parallel:
      - service: esphome.apollo_msr_1_c2cbe8_play_buzzer
        data:
          song_str: >-
            Jingle
            Bells:d=4,o=5,b=125:8g,8e6,8d6,8c6,2g,8g,8e6,8d6,8c6,2a,8a,8f6,8e6,8d6,8b,8g,8b,8d6,8g.6,16g6,8f6,8d6,2e6,8g,8e6,8d6,8c6,2g,16f#,8g,8e6,8d6,8c6,2a,8a,8f6,8e6,8d6,8g6,16g6,16f#6,16g6,16f#6,16g6,16g#6,8a.6,16g6,8e6,8d6,c6,g6,8e6,8e6,8e.6,16d#6,8e6,8e6,8e.6,16d#6,8e6,8g6,8c.6,16d6,2e6,8f6,8f6,8f.6,16f6,8f6,8e6,8e6,16e6,16e6,8e6,8d6,8d6,8e6,2d6
      - repeat:
          count: 30
          sequence:
            - service: light.turn_on
              target:
                entity_id:
                  - light.apollo_msr_1_c2cbe8_rgb_light
                  - light.apollo_air_1_8518b4_rgb_light
              data:
                rgb_color:
                  - 255
                  - 38
                  - 0
                brightness: 255
                transition: 0
            - delay:
                hours: 0
                minutes: 0
                seconds: 0
                milliseconds: 500
            - service: light.turn_on
              target:
                entity_id:
                  - light.apollo_msr_1_c2cbe8_rgb_light
                  - light.apollo_air_1_8518b4_rgb_light
              data:
                rgb_color:
                  - 0
                  - 249
                  - 0
                brightness: 255
                transition: 0
            - delay:
                hours: 0
                minutes: 0
                seconds: 0
                milliseconds: 500
  - service: light.turn_off
    target:
      entity_id:
        - light.apollo_msr_1_c2cbe8_rgb_light
        - light.apollo_air_1_8518b4_rgb_light
      device_id: []
      area_id: []
    data: {}
mode: single
